VM Automation
infinispan-demos/streaming-data-workshop pull request #19
Opened 2017-10-26 12:05 UTC by tsegismont

Automates the creation of the workshop VM with Packer.

The Fedora 26 VM comes with:

- Oracle JDK
- Maven
- Docker
- Openshift Client (oc)
- IntelliJ CE
- The workshop repo
- Maven dependencies and plugins downloaded

2017-10-26 12:09 UTC, tsegismont commented
@galderz can you take a look ?

There are instructions for building the VM in the commit.

What's missing: Openshift Cluster setup (Infinispan templates included) and images download

2017-10-26 15:27 UTC, galderz commented
Is NVM or Node.js? I use NVM locally but really what's needed here is node 4.2. In the current state of the workshop we need them to run the map UI... Eventually we might just dockerize them and depend on an image that brings what we need.

2017-10-26 15:38 UTC, galderz reviewed
I've not tested but looks good otherwise. I can give it a go tomorrow.

2017-10-26 15:38 UTC, galderz commented on packer/README.adoc
> +- `developer` user with password `password` (_sudoer_)
Following OpenShift's lead of using `developer`/`developer` as usr/pwd for entering the console, I've used that combination for the management access to data grid (for visualizer). Maybe we want to use the same combo here too?

2017-10-26 15:38 UTC, galderz commented on packer/scripts/oc.sh
> +OC_VERSION=3.6.1
Nice! I didn't know they had released a patch version... released 20h ago! :)

2017-10-27 08:46 UTC, galderz commented
I briefly built it and tried it, and it looked good. I didn't run anything yet though. I want to focus on trying out the workshop after the modularization work.

2017-10-30 14:08 UTC, galderz commented
@tsegismont I see you've added 2 commits. Anything else you need to add here?

2017-11-01 07:37 UTC, galderz commented
@tsegismont Anything else to add? I'm planning to build the image this afternoon or tomorrow morning latest for duchess :|

2017-11-02 07:17 UTC, galderz commented
@tsegismont I guess this is done now? I'll integrate later this morning and build an image...

2017-11-02 07:21 UTC, galderz requested changes
The role of `lab_setup` script?

2017-11-02 07:21 UTC, galderz commented on packer/scripts/lab_setup.sh
> +./start-datagrid.sh
I'm not sure about the role of this `lab_setup`, but `start-datagrid.sh` should not be executed by attendees. This is mostly there to start the datagrid via script, but attendees should do that via UI.

2017-11-02 07:26 UTC, galderz commented
In fact, I don't think starting openshift and deploying components should be done on startup.

The idea we've been working with is that the attendees would first start openshift manually via script, create the datagrid, deploy the initial play with cache verticle, then deploy all components with their gaps in the code.

2017-11-02 07:29 UTC, galderz commented
Maybe `lab_setup` is just a manual helper script for users to call? :|

I'm integrating it as is and I'll see how it goes.

2017-11-02 07:29 UTC, merged